### ISSUE TITLE
Eu language

### ISSUE THREAD

**Issue by gboquizosanchez** [MohmmedAshraf/blade-flags#1]
Hi!

I think this flag for [euskara language](https://github.com/MohmmedAshraf/blade-flags/blob/main/resources/svg/language-eu.svg) is [Saint Pierre and Miquelon](https://en.wikipedia.org/wiki/Flag_of_Saint_Pierre_and_Miquelon) French comune. It's true they still use the euskara language.

But probably, [Basque Country](https://en.wikipedia.org/wiki/Basque_Country_(autonomous_community)) is the main place of the Euskara language.

Can you change that flag for [this](https://en.wikipedia.org/wiki/Ikurri%C3%B1a)?

Thanks in advance.

**Comment by MohmmedAshraf** [comment]
Hi, @gboquizosanchez 

correct me if I'm wrong, but after some research, I found the Basque language flag should be 🇪🇸 Spain's flag, if so this will be fixed in the next release.

Thanks

**Comment by gboquizosanchez** [comment]
This language is used mainly in Basque Country that is part of Spain, yeah. But I don't think Spain flag be a good idea for basque language, because it doesn't represent the language itself...

**Comment by MohmmedAshraf** [comment]
@gboquizosanchez Well you will have it in the next release, Thanks

**Comment by gboquizosanchez** [comment]
Thanks!
