### ISSUE TITLE
Why provide flag for language ?

### ISSUE THREAD

**Issue by mrleblanc101** [MohmmedAshraf/blade-flags#2]
Isn't it a bit confusing and opinionated ?

Why is English the flag of Britain, that would be confusing for an American.

Same for Spanish, would be confusing for a Mexican if you use Spain flag.

What's the standard/logic behind the flag choice for the languages ?

**Comment by mrleblanc101** [comment]
Apple finally got rid of the flags in the input type picker for this exact reason. It's bad practice.

Before:
![image](https://user-images.githubusercontent.com/17392251/202832422-20fc0122-6fa6-4c80-ae44-8b8ddede78cc.png)

After:
![image](https://user-images.githubusercontent.com/17392251/202832425-19e5856b-9b82-4615-af56-beef225f7136.png)

Here's a exemple with a Russian speaking Ukrainian that don't want to be associate with the Russian flag: https://discussions.apple.com/thread/253751126

Maybe it would be better to change the icon to a glyph like Apple or otherwise remove the Language Flag option. People can always match the flag to language manually if they like and use the correct variation for their app context. (i.e. A UK flag or a USA flag for English)

**Comment by SPiercer** [comment]
@mrleblanc101 
English is originated in Britain as same as Spanish in Spain,

There's literally no difference lingual between American and British as they are both English.

the only difference can be in input types because of the keyboard layout that's all, whereas this package is not intended for input layout only.

if you want to change something feel free to fork the package and open a pull request to make those glyph icons

**Comment by mrleblanc101** [comment]
A lot of language have more obscure origin, a lot of language would share the same flag too. India has 9 different languages for exemple.

Language do not have flag, why force a flag to something that hasn't one ? 

With svg inlining, you could completely control/override the language flag style like this:

```SCSS
.language-flag {
  background: black;
  color: white;
  // or
  background: red;
  color: transparent;
  opacity: 0.5;
}
```

**Comment by SPiercer** [comment]
> if you want to change something feel free to fork the package and open a pull request to make those glyph icons

**Comment by mrleblanc101** [comment]
I won't waste my time if you're not open to the idea like you seem to be from your other comments.

Also, more thinking would need to be done. Monochrome glyph (like black background and white/transparent text) won't work with every design and since the SVG and in `<img />` tag instead of being inined as `<svg>` element, there would be no way to style them.

**Comment by MohmmedAshraf** [comment]
@mrleblanc101 Thank you for your feedback, your opinion will be considered in the next release, i will work on it as soon as possible.

I will be closing this issue for now.

**Comment by jcc5018** [comment]
> There's literally no difference lingual between American and British as they are both English.

There is differences between English languages when it comes to spelling.   American English may have something spelled color whereas British English would be colour  and many other examples. Britain's also tend to use S where Americans would use Z

Not sure is Australia has its own differences, or which it leans toward.
