### ISSUE TITLE
syntax error, unexpected token "<" while using dynamic example

### ISSUE THREAD

**Issue by shailesh-ladumor** [MohmmedAshraf/blade-flags#6]
When I use dynamic version and pass variables. it's throwing an error. can you please let me know what's the issue.
Code
![image](https://user-images.githubusercontent.com/16555999/207214800-1b7bf67d-5143-481d-a780-eeb0e3fd1700.png)

Output

![image](https://user-images.githubusercontent.com/16555999/207214859-320a2405-a56c-4719-ba2f-3badf80feb45.png)

Laravel v9.43.0 (PHP v8.1.0)

**Comment by MohmmedAshraf** [comment]
@shailesh-ladumor Hi, the readme file has been updated, 

Thank you for your feedback.
