### ISSUE TITLE
Unable to locate a class or view for component [flag-country-yu].

### ISSUE THREAD

**Issue by BenOussama180** [MohmmedAshraf/blade-flags#8]
cant find flag for : 
'YU' => 'Yugoslavia',

**Comment by MohmmedAshraf** [comment]
Will be added in the next release, Thank you @BenOussama180

**Comment by BenOussama180** [comment]
> Will be added in the next release, Thank you @BenOussama180 

is there any way to check if the dynamic compoenent exists and only then render it ? because i dont know how to fix this issue in my code

**Comment by BenOussama180** [comment]
> > Will be added in the next release, Thank you @BenOussama180 
> 
> is there any way to check if the dynamic compoenent exists and only then render it ? because i dont know how to fix this issue in my code

i tried with View::exists but it wont render anything

**Comment by MohmmedAshraf** [comment]
I've tried to do this, but can't find a solution for it I will try to work around maybe I can find a way to prevent this from happening

**Comment by MohmmedAshraf** [comment]
@BenOussama180 give me 2 hours I will add this flag for you, Thanks

**Comment by BenOussama180** [comment]
> @BenOussama180 give me 2 hours I will add this flag for you, Thanks

thanks alot , no rush take your time!

**Comment by MohmmedAshraf** [comment]
@BenOussama180 released
