### ISSUE TITLE
appears  to be missing Israel Flag  + a suggestion

### ISSUE THREAD

**Issue by jcc5018** [MohmmedAshraf/blade-flags#9]
It appears to be missing IL- Israel

Also, for fallback setting, what do you actually insert into that setting? the file name? Do you include ".svg"?   I'm loading my files dynamically.   

You may want to add to documentation that country codes need to be lowercase to be found, as my DB entries are capitalized and it didn't work till I made them lowercase. 

Thanks for providing this.

**Comment by MohmmedAshraf** [comment]
I will be adding the flag to the package in the next release. 

> Also, for the fallback setting, what do you actually insert into that setting? the file name? Do you include ".svg"? I'm loading my files dynamically.

I have added default fallback in the config `'fallback' => 'flag-country-xx'`

> You may want to add to documentation that country codes need to be lowercase to be found, as my DB entries are capitalized and it didn't work till I made them lowercase.

I will update the readme file.

Thank you, @jcc5018

**Comment by MohmmedAshraf** [comment]
@jcc5018 released

**Comment by jcc5018** [comment]
Thanks
